// react/src/App.jsx
import ExampleComponent from "./components/SettingUpAComponent";
// import ExampleComponent from "./components/StylingComponents";
// import ExampleComponent from "./components/ExternalStyles";
// import Card from "./components/Card";
// import ExampleComponent from "./components/StateManagementWithReactivity";
// import Counter from "./components/Counter";
// import DoubleCounter from "./components/DoubleCounter";
// import ExampleComponent from "./components/LifecycleHooks";
// import ExampleComponent from "./components/WatchingAndTrackingChanges";
// import ExampleComponent from "./components/ConditionalRendering";
// import Parent from "./components/PassingPropsToChildComponents";
// import ExampleComponent from "./components/PassingComponentsInSlots";
// import ExampleComponent from "./components/HandlingEventsBetweenParentAndChildComponents";
// import ExampleComponent from "./components/AccessingDOMElementsWithRefs";
// import ExampleComponent from "./components/ReusableLogic";

function App() {
    return (
        <>
            {/* Use the components from the Components directory here */}
            <ExampleComponent />
            {/* <Card /> */}
            {/* <Counter /> */}
            {/* <DoubleCounter /> */}
            {/* <Parent /> */}
        </>
    );
}

export default App;

// vue/src/App.vue
<script setup>
// import SettingUpAComponent from "./components/SettingUpAComponent.vue";
// import StylingComponents from "./components/StylingComponents.vue";
// import ExternalStyles from "./components/ExternalStyles.vue";
// import ScopedStyles from "./components/ScopedStyles.vue";
// import StateManagementWithReactivityRef from "./components/StateManagementWithReactivityRef.vue";
// import StateManagementWithReactivityReactive from "./components/StateManagementWithReactivityReactive.vue";
// import StateManagementWithReactivityComputed from "./components/StateManagementWithReactivityComputed.vue";
// import LifecycleHooks from "./components/LifecycleHooks.vue";
// import WatchingAndTrackingChanges from "./components/WatchingAndTrackingChanges.vue";
// import ConditionalRendering from "./components/ConditionalRendering.vue";
// import ParentProps from "./components/Parent.vue";
// import ParentSlot from "./components/ParentSlot.vue";
// import ParentEvents from "./components/ParentEvents.vue";
// import AccessingDOMElementsWithRefs from "./components/AccessingDOMElementsWithRefs.vue";
// import Component from "./components/Component.vue";
// import ComponentA from "./components/ComponentA.vue";
// import ComponentB from "./components/ComponentB.vue";
</script>

<template>
    <!-- Use the components from the Components directory here -->
    <!-- <SettingUpAComponent /> -->
    <!-- <ExternalStyles /> -->
    <!-- <StylingComponents /> -->
    <!-- <ScopedStyles /> -->
    <!-- <StateManagementWithReactivityRef /> -->
    <!-- <StateManagementWithReactivityReactive /> -->
    <!-- <StateManagementWithReactivityComputed /> -->
    <!-- <LifecycleHooks /> -->
    <!-- <WatchingAndTrackingChanges /> -->
    <!-- <ConditionalRendering /> -->
    <!-- <ParentProps /> -->
    <!-- <ParentSlot /> -->
    <!-- <ParentEvents /> -->
    <!-- <AccessingDOMElementsWithRefs /> -->
    <!-- <Component /> -->
    <!-- <ComponentA />
    <ComponentB /> -->
</template>
